### ISSUE TITLE
Book animation

### ISSUE THREAD

**Issue by hamen** [yankai-victor/Loading#1]
Hi
Is it possible to change the color?
Thank you

**Comment by yankai-victor** [comment]
Thanks for your attention.

Yes.
There are three items in the color.xml. 
```
<color name="book_loading_background">#ffffff</color>
<color name="book_loading_book">#ff33b5e5</color>
<color name="book_loading_page">#ffffff</color>
```

You can define the three items in your app module as you want.
And the color will be override.

**Comment by hamen** [comment]
This is great! I'm planning to use your animation in Kindle Gratis (https://play.google.com/store/apps/details?id=org.dronix.android.kindlegratis)
I think is very appropriate :smile:

**Comment by yankai-victor** [comment]
Wow!
Thank you!
