### ISSUE TITLE
适配bug

### ISSUE THREAD

**Issue by xingzhibiao** [yankai-victor/Loading#18]
大神，翻书刷新 在华为7.0上 不刷新  求教

**Comment by yankai-victor** [comment]
有logcat日志吗

**Comment by xingzhibiao** [comment]
12-18 15:06:20.994 19832-19832/com.victor.loading.example I/hwaps: JNI_OnLoad
12-18 15:06:21.104 19832-19832/com.victor.loading.example V/AudioManager: playSoundEffect   effectType: 0
12-18 15:06:21.104 19832-19832/com.victor.loading.example V/AudioManager: querySoundEffectsEnabled...
12-18 15:06:21.143 19832-19832/com.victor.loading.example D/HwCust: Create obj success use class android.app.HwCustActivityImpl
12-18 15:06:21.145 19832-19832/com.victor.loading.example D/HwCust: Create obj success use class android.app.HwCustHwWallpaperManagerImpl
12-18 15:06:21.147 19832-19832/com.victor.loading.example V/ActivityThread: ActivityThread,callActivityOnCreate
12-18 15:06:21.208 19832-19832/com.victor.loading.example E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
12-18 15:06:21.209 19832-19832/com.victor.loading.example E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
12-18 15:06:21.211 19832-19832/com.victor.loading.example E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
12-18 15:06:21.213 19832-19832/com.victor.loading.example E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
12-18 15:06:21.214 19832-19832/com.victor.loading.example E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
12-18 15:06:21.216 19832-19832/com.victor.loading.example D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f080000, context : com.victor.loading.example.BookActivity@e9b62a7, Nhwext : 0, get Blur : disable with , null
12-18 15:06:21.218 19832-19832/com.victor.loading.example D/ActivityThread: add activity client record, r= ActivityRecord{4621354 token=android.os.BinderProxy@5e45e53 {com.victor.loading.example/com.victor.loading.example.BookActivity}} token= android.os.BinderProxy@5e45e53
12-18 15:06:21.222 19832-19832/com.victor.loading.example I/HwPointEventFilter: do not support AFT because of no config
12-18 15:06:21.225 19832-19832/com.victor.loading.example I/ActivityManager_activity: Resuming ActivityRecord{4621354 token=android.os.BinderProxy@5e45e53 {com.victor.loading.example/com.victor.loading.example.BookActivity}} with isForward=true,forwardBitChanged=false onlyLocalRequest=false
12-18 15:06:21.257 19832-19854/com.victor.loading.example D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
12-18 15:06:21.281 19832-19854/com.victor.loading.example E/OpenGLRenderer: allen debug liyu Key: 0
12-18 15:06:21.282 19832-19854/com.victor.loading.example E/OpenGLRenderer: allen debug liyu Key: 68719476736
12-18 15:06:21.283 19832-19854/com.victor.loading.example E/OpenGLRenderer: allen debug liyu Key: 34359738371
12-18 15:06:21.290 19832-19832/com.victor.loading.example I/ActivityManager_activity: Reporting idle of ActivityRecord{4621354 token=android.os.BinderProxy@5e45e53 {com.victor.loading.example/com.victor.loading.example.BookActivity}} finished=false
12-18 15:06:23.563 19832-19832/com.victor.loading.example V/AudioManager: playSoundEffect   effectType: 0
12-18 15:06:23.563 19832-19832/com.victor.loading.example V/AudioManager: querySoundEffectsEnabled...

**Comment by yankai-victor** [comment]
试了一下华为8.0的系统没问题，这个日志感觉没有具体的报错信息啊

**Comment by xingzhibiao** [comment]
应该是全部Log，Verbose级别的   我再看看Log吧   到时再联系你 ，大神

**Comment by xingzhibiao** [comment]
我又看了一遍 没有有价值的log信息，对于这种不崩溃又不好使的代码 该怎么找到解决方法呢？

**Comment by yankai-victor** [comment]
只有华为的7.0有问题，可以把apk装到其他的机型和系统版本上看看。然后用debug在从动画开始那里看看程序有没有正常往下走。

**Comment by xingzhibiao** [comment]
好 谢谢大神
