### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by tellfa** [yankai-victor/Loading#2]
hi, how to use this ?
tnx

**Comment by yankai-victor** [comment]
Clone this project with git. And import into Android Studio. For the more detail, I think you can google it.
If you want to use one of the loading view. You may need to copy the code to your project. It's a little inconvenience.
I'm still thinking to get a better way.

**Comment by Ydcool** [comment]
You can upload this library to jcenter or maven central.

**Comment by yankai-victor** [comment]
@Ydcool 
You can see this http://android-arsenal.com/details/1/2295.

**Comment by veiz** [comment]
Thanks for this, as @Ydcool said, it's better to upload this project to jcenter or maven central, then it will be simply imported by one line configuration like 
`compile 'com.nineoldandroids:library:2.4.0'`

**Comment by yankai-victor** [comment]
@veiz 
Fine，I'll do it later.
Thanks for your advice.

**Comment by nickzhanglv** [comment]
I can't change color

**Comment by yankai-victor** [comment]
@nickzhanglv 
Sorry, can you give me more information?

**Comment by nickzhanglv** [comment]
how can i change rotate Loading color ? default color is white , how can I change to other color.
I user xml config   (app:loading_color="@color/yellow" ) doesn't work.  still white color.
<com.victor.loading.rotate.RotateLoading
        android:id="@+id/rotateloading"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_centerInParent="true"
        app:loading_color="@color/yellow"
        app:loading_width="3dp" />

**Comment by yankai-victor** [comment]
@nickzhanglv 
Sorry, it was a bug. I fixed it.
Thank you.

**Comment by nickzhanglv** [comment]
Cool!  Thanks.  You’ve been a big help.

**Comment by yankai-victor** [comment]
@nickzhanglv 
Glad to hear that.
