### ISSUE TITLE
Changing color

### ISSUE THREAD

**Issue by jkwiecien** [yankai-victor/Loading#4]
No custom color supported? Just white?

**Comment by yankai-victor** [comment]
@jkwiecien 
RotateLoading and BookLoading can change color. You can read the wiki.
[RotateLoading](https://github.com/yankai-victor/Loading/wiki/RotateLoading)
[BookLoading](https://github.com/yankai-victor/Loading/wiki/BookLoading)

**Comment by Fanalys** [comment]
Hi ! 

I'm using RotateLoading and I put my own color but it's always white. 
Here my XML:
```XML 
        <com.victor.loading.rotate.RotateLoading
            android:id="@+id/progress_ticket"
            android:layout_width="40dp"
            android:layout_height="40dp"
            app:loading_width="5dp"
            app:loading_color="@color/colorAccent"
            android:layout_centerInParent="true"
            android:layout_gravity="center_horizontal"/>
```

Thanks for the help!

**Comment by yankai-victor** [comment]
@Fanalys 
Sorry, this was a bug. But I already fixed it.
You can use the latest version. And try again.

**Comment by Fanalys** [comment]
@yankai-victor I'm using your latest version (1.0.1) and it's always white.. /:

**Comment by 13120241790** [comment]
change color now is OK?
thanks

**Comment by 13120241790** [comment]
- -原来是武汉的噢 我还去写蹩脚的英语. 我看你最后一次 提交是 8个月前 请问一下 变化颜色的 问题 fix 了吗？

**Comment by yankai-victor** [comment]
@13120241790 
Yes, already fixed.
毕竟有歪果仁在，还是英语好些。

**Comment by 13120241790** [comment]
兄弟自定义控件水平相当之高啊  求你 QQ 让我膜拜一下

**Comment by 13120241790** [comment]
颜开兄 在否？
