### ISSUE TITLE
Change color programmatically

### ISSUE THREAD

**Issue by marinica94** [yankai-victor/Loading#6]
can the color be changed programmatically ?

btw, good job with the library, awesome job.

**Comment by jamrader** [comment]
I was wondering the same thing -- can it even be changed in xml? The property "loading_color" has no effect for me.

**Comment by marinica94** [comment]
On me
​ it's working from XML, update the library to the last version and check
again.​

**Comment by yankai-victor** [comment]
Hi, I add some code to change the color programmatically.
You can check it in last version :)

**Comment by yankai-victor** [comment]
> I was wondering the same thing -- can it even be changed in xml? The property "loading_color" has no effect for me.

As marinica94 said, please update the library to the last version.

**Comment by marinica94** [comment]
Is the latest version available or you need to pull it ?

**Comment by marinica94** [comment]
Nvm, I have solved it, I don't know why android studio started not to notificate me about library updates
