### ISSUE TITLE
attribute setting problem for RotateLoading

### ISSUE THREAD

**Issue by miladna7** [yankai-victor/Loading#8]
Hello dear.
i have problem to set:
app:loading_speed="11"
app:loading_width="1dp" (this one is so important  for me, because i want use RotateLoading in small size)
this two not working and this one:
app:loading_color="#f4f3"
this one is change between some dark colors or if i don't set any thing, it goes to default one.
and thanks for your amazing library.

**Comment by yankai-victor** [comment]
I try this code
```xml
<com.victor.loading.rotate.RotateLoading
        android:id="@+id/rotateloading"
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:layout_centerInParent="true"
        app:loading_speed="5"
        app:loading_color="#f4f3"
        app:loading_width="1dp" />
```
and it works fine.
Do you use the latest version? May I see your code about RotateLoading?

**Comment by miladna7** [comment]
one, sorry for delay.
second, i found why thing do not act right: in root tag of my layout, for app: , inserted this:
`  xmlns:app="http://schemas.android.com/tools"` 
and when i changed it to:
`  xmlns:app="http://schemas.android.com/apk/res-auto"`
every thing back to normal.
and last but not least, thank u, for your amazing library.

**Comment by yankai-victor** [comment]
Glad you like it
